### ISSUE TITLE
torus_direct ^2.1.0 which doesn't match any versions, version solving failed

### ISSUE THREAD

**Issue by kineticac** [torusresearch/customauth-flutter-sdk#11]
I am trying to add the SDK

In my pubspec.yaml

`torus_direct: ^2.1.0`

I am trying to add the latest version, but it looks like the only thing I can get is 2.0.0 right now.

Anyway this could be updated?

**Comment by phuctm97** [comment]
We're having issues with pub.dev, please use git packages for now:

```
dependencies:
  kittens:
    git:
      url: git@github.com:torusresearch/customauth-flutter-sdk.git
      ref: v2.1.0
```
